# @package _global_

model:
  _target_: sklearn.ensemble.GradientBoostingClassifier
  n_estimators: 100
  max_depth: 5
  learning_rate: 0.1
  random_state: ${project.random_state}

model_name: gradient_boosting
model_path: models/gb_model.pkl
metrics_path: models/gb_metrics.json
