# @package _global_

model:
  _target_: sklearn.linear_model.LogisticRegression
  C: 1.0
  random_state: ${project.random_state}
  max_iter: 1000
  class_weight: balanced

model_name: logistic_regression
model_path: models/lr_model.pkl
metrics_path: models/lr_metrics.json
