# @package _global_

model:
  _target_: sklearn.ensemble.RandomForestClassifier
  n_estimators: 100
  max_depth: 8
  random_state: ${project.random_state}
  n_jobs: -1
  class_weight: balanced

model_name: random_forest
model_path: models/rf_model.pkl
metrics_path: models/rf_metrics.json
